name: horologist-ci

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: yarn

            - name: Run Horologist Tests
              run: yarn horologist test
